# build only master branch on commit's
# all other branches build on PullRequest creation
branches:
  only:
    - master

language: rust

rust:
# build nightly only for the time beeing
  - nightly

env:
# each line hear should trigger a different build, using all folders where we
# would like to build in in an env variable
  - BUILD_DIR=./
  - BUILD_DIR=./scenario-1
  - BUILD_DIR=./scenario-2

matrix:
  fast_finish: true

script: cd $BUILD_DIR && ./travis-build.sh

install:
# install cross compiler toolchain
  - sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
# install cargo xbuild to proper cross compile  
  - cargo install cargo-xbuild
# add the build target used for Raspbarry Pi targeting builds
  - rustup target add armv7-unknown-linux-gnueabihf
  - rustup component add rust-src
  - sudo chmod ugo+x ./travis-build.sh
  - sudo chmod ugo+x ./scenario-1/travis-build.sh
  - sudo chmod ugo+x ./scenario-2/travis-build.sh