[package]
name = "rpi-kernel"
version = "0.0.1"
edition = "2018"

[[bin]]
name ="kernel7"
path = "src/kernel.rs"

[dependencies.ruspiro-sdk]
path = "../."
version = "0.2"
default-features = false
features = ["ruspiro_pi3"]