[package]
name = "rpi-kernel"
version = "0.0.1"
edition = "2018"

[[bin]]
name ="kernel7"
path = "src/kernel.rs"

[dependencies]
ruspiro-sdk = { path = "../../ruspiro-sdk", features = [
        "ruspiro_pi3"
    ] }

[patch.crates-io]
ruspiro-interrupt = { path = "../../ruspiro-interrupt" }